/* Place all your action type strings here */

export const STATE_FINDING_RETAILER = 'STATE_FINDING_RETAILER';
export const STATE_AWAITING_RETAILER_CONFIRMATION = 'STATE_AWAITING_RETAILER_CONFIRMATION';
export const STATE_FINDING_DELIVERER = 'STATE_FINDING_DELIVERER';
export const STATE_AWAITING_DELIVERER_CONFIRMATION = 'STATE_AWAITING_DELIVERER_CONFIRMATION';
export const STATE_AWAITING_DELIVERY_PICK_UP = 'STATE_AWAITING_DELIVERY_PICK_UP';
export const STATE_ON_ROUTE = 'STATE_ON_ROUTE';
export const STATE_DELIVERED = 'STATE_DELIVERED';
export const STATE_CANCELLED = 'STATE_CANCELLED';
export const REQUEST_FETCH_ORDERS_LIST = 'REQUEST_FETCH_ORDERS_LIST'

export const REQUEST_ASSIGN_ORDER = 'REQUEST_ASSIGN_ORDER'
export const REQUEST_FETCH_ORDERS_DATA = 'REQUEST_FETCH_ORDERS_DATA'
export const SUCCESS_FETCH_ORDERS_DATA = 'SUCCESS_FETCH_ORDERS_DATA'
export const REQUEST_FILTER_ORDERS_DATA = 'REQUEST_FILTER_ORDERS_DATA'
export const SUCCESS_FILTER_ORDERS_DATA = 'SUCCESS_FILTER_ORDERS_DATA'
