/* Place all your action type strings here */

// export const STATE_FINDING_RETAILER = 'STATE_FINDING_RETAILER';
// export const STATE_AWAITING_RETAILER_CONFIRMATION = 'STATE_AWAITING_RETAILER_CONFIRMATION';
// export const STATE_FINDING_DELIVERER = 'STATE_FINDING_DELIVERER';
// export const STATE_AWAITING_DELIVERER_CONFIRMATION = 'STATE_AWAITING_DELIVERER_CONFIRMATION';
// export const STATE_AWAITING_DELIVERY_PICK_UP = 'STATE_AWAITING_DELIVERY_PICK_UP';
// export const STATE_ON_ROUTE = 'STATE_ON_ROUTE';
// export const STATE_DELIVERED = 'STATE_DELIVERED';
// export const STATE_CANCELLED = 'STATE_CANCELLED';
// export const REQUEST_FETCH_ORDERS_LIST = 'REQUEST_FETCH_ORDERS_LIST'

export const REQUEST_ASSIGN_ORDER = 'REQUEST_ASSIGN_ORDER'
export const SUCCESS_ASSIGN_ORDER = 'SUCCESS_ASSIGN_ORDER'

export const REQUEST_FETCH_ORDERS_DATA = 'REQUEST_FETCH_ORDERS_DATA'
export const SUCCESS_FETCH_ORDERS_DATA = 'SUCCESS_FETCH_ORDERS_DATA'

export const REQUEST_FETCH_LIVE_ORDERS = 'REQUEST_FETCH_LIVE_ORDERS'
export const SUCCESS_FETCH_LIVE_ORDERS = 'SUCCESS_FETCH_LIVE_ORDERS'

export const REQUEST_FETCH_LIVE_ASSIGNED_ORDERS = 'REQUEST_FETCH_LIVE_ASSIGNED_ORDERS'
export const SUCCESS_FETCH_LIVE_ASSIGNED_ORDERS = 'SUCCESS_FETCH_LIVE_ASSIGNED_ORDERS'

export const REQUEST_FETCH_LIVE_UNASSIGNED_ORDERS = 'REQUEST_FETCH_LIVE_UNASSIGNED_ORDERS'
export const SUCCESS_FETCH_LIVE_UNASSIGNED_ORDERS = 'SUCCESS_FETCH_LIVE_UNASSIGNED_ORDERS'

export const REQUEST_FETCH_HISTORY_ORDERS = 'REQUEST_FETCH_HISTORY_ORDERS'
export const SUCCESS_FETCH_HISTORY_ORDERS = 'SUCCESS_FETCH_HISTORY_ORDERS'

export const REQUEST_FETCH_CANCELLATION_ORDERS = 'REQUEST_FETCH_CANCELLATION_ORDERS'
export const SUCCESS_FETCH_CANCELLATION_ORDERS = 'SUCCESS_FETCH_CANCELLATION_ORDERS'

export const REQUEST_FETCH_ATTEMPTED_ORDERS = 'REQUEST_FETCH_ATTEMPTED_ORDERS'
export const SUCCESS_FETCH_ATTEMPTED_ORDERS = 'SUCCESS_FETCH_ATTEMPTED_ORDERS'

export const REQUEST_SEARCH_LIVE_ORDERS = 'REQUEST_SEARCH_LIVE_ORDERS'
export const SUCCESS_SEARCH_LIVE_ORDERS = 'SUCCESS_SEARCH_LIVE_ORDERS'

export const REQUEST_SEARCH_LIVE_ASSIGNED_ORDERS = 'REQUEST_SEARCH_LIVE_ASSIGNED_ORDERS'
export const SUCCESS_SEARCH_LIVE_ASSIGNED_ORDERS = 'SUCCESS_SEARCH_LIVE_ASSIGNED_ORDERS'

export const REQUEST_SEARCH_LIVE_UNASSIGNED_ORDERS = 'REQUEST_SEARCH_LIVE_UNASSIGNED_ORDERS'
export const SUCCESS_SEARCH_LIVE_UNASSIGNED_ORDERS = 'SUCCESS_SEARCH_LIVE_UNASSIGNED_ORDERS'

export const REQUEST_SEARCH_HISTORY_ORDERS = 'REQUEST_SEARCH_HISTORY_ORDERS'
export const SUCCESS_SEARCH_HISTORY_ORDERS = 'SUCCESS_SEARCH_HISTORY_ORDERS'

export const REQUEST_FETCH_ORDER_DETAIL = 'REQUEST_FETCH_ORDER_DETAIL'
export const SUCCESS_FETCH_ORDER_DETAIL = 'SUCCESS_FETCH_ORDER_DETAIL'

export const REQUEST_FILTER_ORDERS_DATA = 'REQUEST_FILTER_ORDERS_DATA'
export const SUCCESS_FILTER_ORDERS_DATA = 'SUCCESS_FILTER_ORDERS_DATA'

export const REQUEST_FORCE_REDEEM = 'REQUEST_FORCE_REDEEM'
export const SUCCESS_FORCE_REDEEM = 'SUCCESS_FORCE_REDEEM'

export const REQUEST_SKIP_RETAILER = 'REQUEST_SKIP_RETAILER'
export const SUCCESS_SKIP_RETAILER = 'SUCCESS_SKIP_RETAILER'

export const REQUEST_SKIP_DELIVERER = 'REQUEST_SKIP_DELIVERER'
export const SUCCESS_SKIP_DELIVERER = 'SUCCESS_SKIP_DELIVERER'

export const REQUEST_CANCEL_ORDER = 'REQUEST_CANCEL_ORDER'
export const SUCCESS_CANCEL_ORDER = 'SUCCESS_CANCEL_ORDER'

export const REQUEST_SET_LOADING_ORDER_DETAIL = 'REQUEST_SET_LOADING_ORDER_DETAIL'
export const SUCCESS_SET_LOADING_ORDER_DETAIL = 'SUCCESS_SET_LOADING_ORDER_DETAIL'

export const REQUEST_CONFIRM_RETAILER = 'REQUEST_CONFIRM_RETAILER'
export const SUCCESS_CONFIRM_RETAILER = 'SUCCESS_CONFIRM_RETAILER'

export const REQUEST_CONFIRM_DELIVERER = 'REQUEST_CONFIRM_DELIVERER'
export const SUCCESS_CONFIRM_DELIVERER = 'SUCCESS_CONFIRM_DELIVERER'

export const REQUEST_AUTO_PILOT = 'REQUEST_AUTO_PILOT'
export const SUCCESS_AUTO_PILOT = 'SUCCESS_AUTO_PILOT'

export const REQUEST_FETCH_AUTO_PILOT_STATUS = 'REQUEST_FETCH_AUTO_PILOT_STATUS'
export const SUCCESS_FETCH_AUTO_PILOT_STATUS = 'SUCCESS_FETCH_AUTO_PILOT_STATUS'

export const REQUEST_FETCH_PLOT_DATA = 'REQUEST_FETCH_PLOT_DATA'
export const SUCCESS_FETCH_PLOT_DATA = 'SUCCESS_FETCH_PLOT_DATA'
