export const STATE_FINDING_RETAILER = 'STATE_FINDING_RETAILER';
export const STATE_AWAITING_RETAILER_CONFIRMATION = 'STATE_AWAITING_RETAILER_CONFIRMATION';
export const STATE_FINDING_DELIVERER = 'STATE_FINDING_DELIVERER';
export const STATE_AWAITING_DELIVERER_CONFIRMATION = 'STATE_AWAITING_DELIVERER_CONFIRMATION';
export const STATE_AWAITING_DELIVERY_PICK_UP = 'STATE_AWAITING_DELIVERY_PICK_UP';
export const STATE_ON_ROUTE = 'STATE_ON_ROUTE';
export const STATE_DELIVERED = 'STATE_DELIVERED';
export const STATE_CANCELLED = 'STATE_CANCELLED';
